"""Add deleted account status

Revision ID: 002125cefa34
Revises: 6e657a40b57a
Create Date: 2025-09-27 10:42:22.676971

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002125cefa34'
down_revision: Union[str, Sequence[str], None] = '6e657a40b57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE accountstate ADD VALUE 'DELETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.execute("""
        UPDATE user_account 
        SET account_state = 'SUSPENDED'::accountstate 
        WHERE account_state::text = 'DELETED'
    """)
    
    op.execute("ALTER TYPE accountstate RENAME TO accountstate_old")
    
    account_state_enum = postgresql.ENUM(
        'ACTIVE', 'SUSPENDED', 
        name='accountstate'
    )
    account_state_enum.create(op.get_bind())
    
    op.execute("""
        ALTER TABLE user_account 
        ALTER COLUMN account_state TYPE accountstate 
        USING account_state::text::accountstate
    """)
    
    op.execute("DROP TYPE accountstate_old")
    # ### end Alembic commands ###
