"""added user_account.account_state

Revision ID: 368542b1db41
Revises: f86f2d54aa25
Create Date: 2025-08-11 22:55:41.309968

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368542b1db41'
down_revision: Union[str, Sequence[str], None] = 'f86f2d54aa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_state_enum = postgresql.ENUM(
        'ACTIVE',
        'SUSPENDED',
        name='accountstate'
    )
    account_state_enum.create(op.get_bind()) 

    op.add_column(
        'user_account', 
        sa.Column(
            'account_state', 
            account_state_enum, 
            server_default='ACTIVE', 
            nullable=False
        )
    )
    op.alter_column('user_account', 'account_state', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'account_state')

    account_state_enum = postgresql.ENUM(
        'ACTIVE',
        'SUSPENDED',
        name='accountstate'
    )
    account_state_enum.drop(op.get_bind())
    # ### end Alembic commands ###
