"""Add account suspension reason

Revision ID: 56e905c92343
Revises: 002125cefa34
Create Date: 2025-09-27 10:59:44.156446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e905c92343'
down_revision: Union[str, Sequence[str], None] = '002125cefa34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('suspension_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'suspension_reason')
    # ### end Alembic commands ###
