"""Added book.on_loan and booktransaction.transaction_type

Revision ID: 721ef0b6f689
Revises: 368542b1db41
Create Date: 2025-08-14 18:40:18.270518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '721ef0b6f689'
down_revision: Union[str, Sequence[str], None] = '368542b1db41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_enum = postgresql.ENUM(
        'BORROW',
        'RETURN',
        name='transactiontype'
    )
    transaction_type_enum.create(op.get_bind()) 

    op.add_column('book', sa.Column('on_loan', sa.Boolean(), server_default='False', nullable=False))
    op.add_column(
        'book_transaction', 
        sa.Column(
            "transaction_type",
            transaction_type_enum, 
            server_default="BORROW", 
            nullable=False
        )
    )
    op.drop_column('book_transaction', 'returned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_transaction', sa.Column('returned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('book_transaction', 'transaction_type')
    op.drop_column('book', 'on_loan')

    transaction_type_enum = postgresql.ENUM(
        'BORROW',
        'RETURN',
        name='transactiontype'
    )
    transaction_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
