"""Added book.on_loan and booktransaction.transaction_type

Revision ID: 721ef0b6f689
Revises: 368542b1db41
Create Date: 2025-08-14 18:40:18.270518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '721ef0b6f689'
down_revision: Union[str, Sequence[str], None] = '368542b1db41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('book', sa.Column('on_loan', sa.Boolean(), server_default='False', nullable=False))

    op.create_table(
        "book_return",
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('book_transaction_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('librarian_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['book_transaction_id'], ['book_transaction.id'], ),
        sa.ForeignKeyConstraint(['librarian_id'], ['user_account.id'], ),
        sa.PrimaryKeyConstraint('id')           
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_return")

    op.drop_column('book', 'on_loan')
    # ### end Alembic commands ###
