"""added Fine.reson

Revision ID: f86f2d54aa25
Revises: a14ea8ec0302
Create Date: 2025-08-10 15:43:12.173918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86f2d54aa25'
down_revision: Union[str, Sequence[str], None] = 'a14ea8ec0302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fine", 
        sa.Column('reason', sa.String(), nullable=False, server_default="lorem"))
    op.alter_column('fine', 'reason', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fine", "reason")
    # ### end Alembic commands ###
