"""Add book_transaction.extended

Revision ID: fa1ec11de3fa
Revises: 31e6ea4e0dfa
Create Date: 2025-08-18 19:19:58.693891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fa1ec11de3fa'
down_revision: Union[str, Sequence[str], None] = '31e6ea4e0dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_transaction', sa.Column('extended', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_transaction', 'extended')
    # ### end Alembic commands ###
