name = [
    "Liam Carter", "Olivia Bennett", "Noah Turner", "Emma Collins", "William Harris",
    "Ava Mitchell", "James Brooks", "Sophia Reed", "Benjamin Ward", "Isabella Gray",
    "Lucas Hayes", "Mia Foster", "Henry Morgan", "Charlotte Perry", "Alexander Jenkins",
    "Amelia Bryant", "Ethan Sullivan", "Harper Cooper", "Michael Adams", "Evelyn Torres",
    "Daniel Hughes", "Abigail Price", "Matthew Rivera", "Ella Stewart", "Samuel Long",
    "Scarlett Rogers", "Joseph Butler", "Victoria Barnes", "David Simmons", "Luna Coleman",
    "Andrew Powell", "Grace Howard", "Joshua Sanders", "Chloe Ross", "Christopher Peterson",
    "Penelope Morris", "Gabriel Jenkins", "Layla Reed", "Anthony Murphy", "Riley Kelly",
    "Isaac Evans", "Zoey Cox", "Nathan Ward", "Hannah Foster", "Thomas Brooks",
    "Aria Cook", "Leo Murphy", "Camila Parker", "Owen Mitchell", "Lily Gonzales",
    "Julian Howard", "Nora Russell", "Jack Diaz", "Ellie Powell", "Aaron Foster",
    "Hazel Simmons", "Caleb Perry", "Aurora James", "Charles Watson", "Savannah Price",
    "Christopher Cooper", "Addison Barnes", "Miles Rivera", "Stella Murphy", "Eli Parker",
    "Paisley Adams", "Jonathan Reed", "Skylar Peterson", "Connor Gray", "Violet Jenkins",
    "Jeremiah Hughes", "Brooklyn Ward", "Adrian Foster", "Claire Sanders", "Hunter James",
    "Lucy Rogers", "Christian Butler", "Anna Stewart", "Colton Hayes", "Everly Howard",
    "Austin Cox", "Naomi Kelly", "Parker Long", "Elena Gonzales", "Adam Torres",
    "Kennedy Hughes", "Zachary Coleman", "Leah Ross", "Evan Powell", "Madeline Foster",
    "Brayden Barnes", "Aubrey Bryant", "Jordan Simmons", "Bella Russell", "Robert Adams",
    "Kinsley Murphy", "Dominic Price", "Maya Mitchell", "Ian Rivera", "Samantha Perry"
]
title = [
    "Endless Shadows", "Cursed Path", "Lost Throne", "Wild Journey", "Brave Flame",
    "Frozen Path", "Hidden Ocean", "Golden River", "Cursed Horizon", "Dark Ocean",
    "Shattered Forest", "Bright Sky", "Ancient Heart", "Secret Crown", "Golden Empire",
    "Frozen Sword", "Sacred Horizon", "Dark Throne", "Hidden Light", "Lost Path",
    "Wild Storm", "Shattered Heart", "Ancient Shadows", "Golden Night", "Sacred Sword",
    "Brave Horizon", "Lonely River", "Frozen Heart", "Wild Flame", "Dark River",
    "Ancient Journey", "Lost Ocean", "Endless Sky", "Hidden Throne", "Bright Path",
    "Golden Horizon", "Cursed Forest", "Sacred Crown", "Burning Empire", "Broken Sword",
    "Frozen Storm", "Bright Horizon", "Dark Shadows", "Ancient Flame", "Secret Ocean",
    "Lonely Crown", "Wild Night", "Brave Ocean", "Cursed River", "Golden Path",
    "Bright Flame", "Hidden Journey", "Shattered Night", "Frozen Light", "Sacred Flame",
    "Ancient Path", "Brave Storm", "Lost River", "Golden Shadows", "Endless Crown",
    "Secret Flame", "Dark Sky", "Lonely Path", "Burning Horizon", "Wild Ocean",
    "Cursed Sky", "Frozen Horizon", "Golden Crown", "Bright Storm", "Lost Horizon",
    "Ancient Storm", "Wild Path", "Hidden River", "Sacred Night", "Endless Light",
    "Brave Crown", "Golden Flame", "Shattered Ocean", "Frozen Empire", "Lonely Horizon",
    "Bright River", "Dark Crown", "Cursed Throne", "Ancient Night", "Wild Horizon",
    "Lost Storm", "Hidden Ocean", "Sacred Path", "Golden Ocean", "Brave Forest",
    "Endless Flame", "Cursed Flame", "Frozen Crown", "Bright Ocean", "Ancient Crown",
    "Wild Flame", "Golden Storm", "Dark Flame", "Hidden Light", "Sacred Forest"
]
description = [
    "A tale of revenge in the golden empire.",
    "A tale of magic in the forgotten kingdom.",
    "A tale of adventure in the dark woods.",
    "A tale of love in the dark woods.",
    "A tale of betrayal in the dark woods.",
    "A tale of magic in the ancient lands.",
    "A tale of revenge in the ancient lands.",
    "A tale of betrayal in the golden empire.",
    "A tale of adventure in the ancient lands.",
    "A tale of adventure in the ancient lands.",
    "A tale of mystery in the forgotten kingdom.",
    "A tale of magic in the golden empire.",
    "A tale of betrayal in the forgotten kingdom.",
    "A tale of love in the ancient lands.",
    "A tale of mystery in the golden empire.",
    "A tale of magic in the stormy seas.",
    "A tale of betrayal in the dark woods.",
    "A tale of adventure in the forgotten kingdom.",
    "A tale of mystery in the dark woods.",
    "A tale of love in the golden empire.",
    "A tale of revenge in the dark woods.",
    "A tale of betrayal in the forgotten kingdom.",
    "A tale of love in the forgotten kingdom.",
    "A tale of adventure in the stormy seas.",
    "A tale of magic in the golden empire.",
    "A tale of betrayal in the ancient lands.",
    "A tale of mystery in the ancient lands.",
    "A tale of love in the golden empire.",
    "A tale of adventure in the stormy seas.",
    "A tale of revenge in the forgotten kingdom.",
    "A tale of betrayal in the golden empire.",
    "A tale of love in the ancient lands.",
    "A tale of magic in the golden empire.",
    "A tale of mystery in the dark woods.",
    "A tale of revenge in the ancient lands.",
    "A tale of betrayal in the stormy seas.",
    "A tale of love in the golden empire.",
    "A tale of magic in the forgotten kingdom.",
    "A tale of adventure in the stormy seas.",
    "A tale of betrayal in the ancient lands.",
    "A tale of magic in the ancient lands.",
    "A tale of revenge in the golden empire.",
    "A tale of betrayal in the forgotten kingdom.",
    "A tale of adventure in the golden empire.",
    "A tale of magic in the forgotten kingdom.",
    "A tale of mystery in the dark woods.",
    "A tale of love in the forgotten kingdom.",
    "A tale of revenge in the ancient lands.",
    "A tale of betrayal in the dark woods.",
    "A tale of mystery in the golden empire.",
    "A tale of magic in the ancient lands.",
    "A tale of revenge in the golden empire.",
    "A tale of betrayal in the stormy seas.",
    "A tale of adventure in the forgotten kingdom.",
    "A tale of love in the dark woods.",
    "A tale of magic in the golden empire.",
    "A tale of betrayal in the ancient lands.",
    "A tale of adventure in the golden empire.",
    "A tale of mystery in the ancient lands.",
    "A tale of revenge in the forgotten kingdom.",
    "A tale of betrayal in the dark woods.",
    "A tale of love in the golden empire.",
    "A tale of magic in the ancient lands.",
    "A tale of adventure in the dark woods.",
    "A tale of betrayal in the forgotten kingdom.",
    "A tale of love in the ancient lands.",
    "A tale of mystery in the golden empire.",
    "A tale of magic in the golden empire.",
    "A tale of revenge in the forgotten kingdom.",
    "A tale of betrayal in the ancient lands.",
    "A tale of love in the dark woods.",
    "A tale of magic in the forgotten kingdom.",
    "A tale of adventure in the golden empire.",
    "A tale of betrayal in the ancient lands.",
    "A tale of love in the forgotten kingdom.",
    "A tale of magic in the golden empire.",
    "A tale of revenge in the ancient lands.",
    "A tale of betrayal in the dark woods.",
    "A tale of mystery in the golden empire.",
    "A tale of love in the ancient lands.",
    "A tale of adventure in the forgotten kingdom.",
    "A tale of betrayal in the stormy seas.",
    "A tale of magic in the golden empire.",
    "A tale of mystery in the dark woods.",
    "A tale of revenge in the golden empire.",
    "A tale of betrayal in the forgotten kingdom.",
    "A tale of love in the ancient lands.",
    "A tale of magic in the golden empire.",
    "A tale of adventure in the stormy seas.",
    "A tale of betrayal in the ancient lands.",
    "A tale of mystery in the forgotten kingdom.",
    "A tale of love in the dark woods.",
    "A tale of revenge in the ancient lands.",
    "A tale of betrayal in the golden empire.",
    "A tale of adventure in the ancient lands.",
    "A tale of mystery in the dark woods.",
    "A tale of magic in the golden empire."
]

fine_reason = [
    "Damaged book",
    "Lost book",
    "Late return"
]
